=begin
#Service API

#filters.

OpenAPI spec version: 1.0.0
Contact: anand@zerebral.co.in
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'event_client/api_client'
require 'event_client/api_error'
require 'event_client/version'
require 'event_client/configuration'

# Models
require 'event_client/models/event'

# APIs
require 'event_client/api/event_api'

module EventClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
